name: Test NumPy

on: [push, pull_request]

jobs:
  test-numpy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install dependencies
      run: pip install numpy
      
    - name: Run NumPy test
      run: python test_numpy.py
